[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  NETLIFY_CACHE_DISABLED = "true"

# Performance optimizations
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Domain handling
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.billit.pro/*"
  to = "https://billit.pro/:splat"
  status = 301
  force = true

# Primary redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = """
      default-src 'self' https://bnfodkbfksjqjfrcksmd.supabase.co;
      style-src 'self' 'unsafe-inline' https://rsms.me;
      img-src 'self' data: https://*.unsplash.com https://*.supabase.co;
      script-src 'self' 'unsafe-inline' https://checkout.razorpay.com;
      connect-src 'self' https://bnfodkbfksjqjfrcksmd.supabase.co https://api.razorpay.com;
      font-src 'self' https://rsms.me;
      frame-src https://checkout.razorpay.com;
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/*.{woff,woff2,ttf,otf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  node_bundler = "esbuild"

[context.production]
  environment = { NODE_VERSION = "20", NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_VERSION = "20", NODE_ENV = "production" }